#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

wmname LG3D &
# only to use in VMWARE instances
# vmware-user-suid-wrapper &

bspc monitor -d I II III IV V VI

bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#30302f'
bspc config presel_feedback_color '#512da8'

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off

find ~/Wallpapers/ -type f | shuf -n 1 | xargs feh --bg-fill &
~/.config/polybar/./launch.sh --cuts &
picom --config ~/.config/picom/picom.conf &
