#!/usr/bin/bash

declare -r myname='checkupdates'
declare -r myver='1.0.0'

error() {
	local mesg=$1
	echo -e "${RED}==> $(gettext "ERROR:")${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" >&2
}

# check if messages are to be printed using color
unset ALL_OFF BOLD RED
if [[ -t 2 && ! $USE_COLOR = "n" ]]; then
	# prefer terminal safe colored and bold text when tput is supported
	if tput setaf 0 &>/dev/null; then
		ALL_OFF="$(tput sgr0)"
		BOLD="$(tput bold)"
		RED="${BOLD}$(tput setaf 1)"
	else
		ALL_OFF="\e[1;0m"
		BOLD="\e[1;1m"
		RED="${BOLD}\e[1;31m"
	fi
fi
readonly ALL_OFF BOLD RED

if (($# > 0)); then
	echo "${myname} v${myver}"
	echo
	echo "Safely print a list of pending updates"
	echo
	echo "Usage: ${myname}"
	echo
	echo 'Note: Export the "CHECKUPDATES_DB" variable to change the path of the temporary database.'
	exit 0
fi

if ! type -P fakeroot >/dev/null; then
	error 'Cannot find the fakeroot binary.'
	exit 1
fi

DIST=$(grep ID /etc/os-release | grep -v _ID | grep -v ID_ | awk -F= '{print $2}')

case "$DIST" in
arch)
	trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT

	if [[ -z $CHECKUPDATES_DB ]]; then
		CHECKUPDATES_DB="${TMPDIR:-/tmp}/checkup-db-${USER}/"
	fi

	DBPath="$(pacman-conf DBPath)"
	if [[ -z "$DBPath" ]] || [[ ! -d "$DBPath" ]]; then
		DBPath="/var/lib/pacman/"
	fi

	mkdir -p "$CHECKUPDATES_DB"
	ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &>/dev/null
	if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &>/dev/null; then
		error 'Cannot configure updates'
		exit 1
	fi
	pacman -Qu --dbpath "$CHECKUPDATES_DB" 2>/dev/null | grep -v '\[.*\]'
	;;

ubuntu | debian)
	if ! apt upgrade -ys &>/dev/null; then
		error 'Cannot configure updates'
		exit 1
	fi
	apt list --upgradable 2>/dev/null | grep -v "Listing..."
	;;
*)
	error 'Distribution not set for upgrades!'
	exit 1
	;;
esac
